# Cloud Build configuration for automatic deployment to Cloud Run
# Triggered on push to main branch via GitHub integration

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/ajay-portfolio/portfolio:$COMMIT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/ajay-portfolio/portfolio:latest'
      - '.'
    id: 'build-image'
  
  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/ajay-portfolio/portfolio:$COMMIT_SHA'
    id: 'push-image'
    waitFor: ['build-image']
  
  # Step 3: Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/ajay-portfolio/portfolio:latest'
    id: 'push-latest'
    waitFor: ['build-image']
  
  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ajay-portfolio'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/ajay-portfolio/portfolio:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--set-env-vars=NODE_ENV=production'
      - '--set-secrets=DATABASE_URL=database-url:latest,RESEND_API_KEY=resend-api-key:latest'
    id: 'deploy-cloud-run'
    waitFor: ['push-image']

# Build configuration
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Images to push to Artifact Registry
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/ajay-portfolio/portfolio:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/ajay-portfolio/portfolio:latest'

# Build timeout (10 minutes)
timeout: 600s
