// Auto-generated by scripts/optimize-timeline-images.ts
// Do not edit manually

export interface TimelineImageSource {
  defaultSrc: string;
  srcSet: string;
  placeholder: string;
  width: number;
  height: number;
  aspectRatio: number;
}

export const TIMELINE_IMAGE_MAP: Record<string, TimelineImageSource> = {
  "timeline/20210521_131718_1756788953660.jpg": {
    "defaultSrc": "/images/timeline/optimized/20210521_131718_1756788953660-w960.webp",
    "srcSet": "/images/timeline/optimized/20210521_131718_1756788953660-w480.webp 480w, /images/timeline/optimized/20210521_131718_1756788953660-w960.webp 960w, /images/timeline/optimized/20210521_131718_1756788953660-w1600.webp 1600w",
    "placeholder": "data:image/webp;base64,UklGRjwBAABXRUJQVlA4IDABAACQBgCdASogABgAPu1iqU2ppaOiMAgBMB2JagC07vA1QU4KDG3aHc5eU1+0E9qxP6E5TgujUcKtXQf/n/9AAOhUGNgirnWWWwhMomQI0TAFMnEUjcOn+lJFB6jOKcKMx7Je5Nikc21Wbmx1gFfYc+OL3mgRNy+7BSt8tmbO2HrZjfaxyFmMn6GwXw+j73TFQ2GnMWpDN7vTUSAYWkMKI2eu0lgaTtKNZzMye3fNNvxtpFgvYBsAL8LSB6XW7BHWtdqgmDjQWHuXcWjOYO9rLY8pWuwQ/adXi0k7J1emUQ7mpyqIRVc6ZL5IHmj6UUA/USJWfguElFC6NmDxDU6dhKnykG3wR2g1E5vNaXirtia+BkfiJ+AV7FJ1+XXL8uKlToQpbIZnqYEdnD/JedaQ2bgA",
    "width": 960,
    "height": 720,
    "aspectRatio": 1.3333333333333333
  },
  "timeline/20210521_213843_1756780555219.jpg": {
    "defaultSrc": "/images/timeline/optimized/20210521_213843_1756780555219-w960.webp",
    "srcSet": "/images/timeline/optimized/20210521_213843_1756780555219-w480.webp 480w, /images/timeline/optimized/20210521_213843_1756780555219-w960.webp 960w, /images/timeline/optimized/20210521_213843_1756780555219-w1600.webp 1600w",
    "placeholder": "data:image/webp;base64,UklGRh4BAABXRUJQVlA4IBIBAAAwBgCdASogABgAPu1eqE2ppSQiN/VYATAdiWYArDMYL2mzuYXey3kPfin0Q87VtJsudVU9sprf8X0AAP7DhA7o3fNKEVkDT75MKoUbwl9daTxZlI4u/iZEmdOmVuulPY0VmfeLD4cHOQ7LnUQQjSH06XFy8gL/DQPO9pqGgTVa3+BqAp5hmtQpiyZYaXyavSa1dgT5gAgtWX2u9SAiD3TBKAOnJbQzaCZrpPXbBzH/jbsaqgzZ6BzEjqHmxXAm6vGVgXRFKD9H6BNgJaTrU63+TTCD2C+8ATPhm+0WnXa8vlguomry2qmPcM+pCX+kkcotjseffY9PuHPvP0jsAhwVtw7niEXXxGJXC3v7mBHR/gAA",
    "width": 960,
    "height": 720,
    "aspectRatio": 1.3333333333333333
  },
  "timeline/20220805_214208_1756776778383.jpg": {
    "defaultSrc": "/images/timeline/optimized/20220805_214208_1756776778383-w960.webp",
    "srcSet": "/images/timeline/optimized/20220805_214208_1756776778383-w480.webp 480w, /images/timeline/optimized/20220805_214208_1756776778383-w960.webp 960w, /images/timeline/optimized/20220805_214208_1756776778383-w1600.webp 1600w",
    "placeholder": "data:image/webp;base64,UklGRuQAAABXRUJQVlA4INgAAADwBACdASogABIAPu1kqU2ppaQiMAgBMB2JQAB84TCuHftsQ+Akb6DPnTZHD1vyPfAA/uzHKgi/+DJVp7DJtuaGjKjfV7/7nKfOhjqQmpxI7GROCcUZTGwQEtjZ8Esr7CCzYyv5727OugM311YDzVkSLHc6jQKbj6/ahX6+ybaoXPRB5pv8CtiNyAAQkUGUS82yEnPyGv2LjlU5+UdwHIzMO5muyfbFw+LmTQu8ZnxiNop576+EcLvOPOYI/ydh13ikvjpL67mS4769+iWE5ML6GE44DcqIAAA=",
    "width": 960,
    "height": 540,
    "aspectRatio": 1.7761989342806395
  },
  "timeline/20231215_095639_1756775804398.jpg": {
    "defaultSrc": "/images/timeline/optimized/20231215_095639_1756775804398-w960.webp",
    "srcSet": "/images/timeline/optimized/20231215_095639_1756775804398-w480.webp 480w, /images/timeline/optimized/20231215_095639_1756775804398-w960.webp 960w, /images/timeline/optimized/20231215_095639_1756775804398-w1600.webp 1600w",
    "placeholder": "data:image/webp;base64,UklGRuwAAABXRUJQVlA4IOAAAACQBQCdASogABIAPu1oq08ppiOiMBgIATAdiUAW2WXLFLy3vFpGnByXTrA1sdcGuawDqOb0AAD+vI1G/42HQ2Atsfbf8H8K32ZLZLZU6NUPrIAqlN9FndztnCjie0Gp12qhq1YCxIeDjgMSoquHJ8MgfGZpy+DWIvn5Jw1EwWM2k0ovqICUheBEN9tV4/IjZCR2WjmPKZNOVfip8N5LzOYabudP5Nbp2DfxBk7UB1NJecmNOMx/r92k7RzvXGiHWdgiwpnAcPAQBE+RmrvuvM/Fmf2luPRR0OEeAvcWBNgAAA==",
    "width": 960,
    "height": 540,
    "aspectRatio": 1.7777777777777777
  },
  "timeline/20240424_161717_1756780061878.jpg": {
    "defaultSrc": "/images/timeline/optimized/20240424_161717_1756780061878-w960.webp",
    "srcSet": "/images/timeline/optimized/20240424_161717_1756780061878-w480.webp 480w, /images/timeline/optimized/20240424_161717_1756780061878-w960.webp 960w, /images/timeline/optimized/20240424_161717_1756780061878-w1600.webp 1600w",
    "placeholder": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAABwBQCdASogABIAPu1oq0+ppiOiMBgIATAdiWUAvzg0c2VbdvPJD120o+iltXl/yxqacrIAAP7DF+PLmQSXYa9HS9nCeDx7SlaOw4e+3GXoqHzhmQU3/KtxxyTyJx43NlLBg65r0JVdZ74fnvEcuT/JzpGjpPiXxZw5IqDPBK+Rn/hCOdp2TeBf5DhdEAPeFsku8Y6EtHM846eqWhwHzHtpEOl1Rmw+alYhAAAA",
    "width": 960,
    "height": 540,
    "aspectRatio": 1.7761989342806395
  },
  "timeline/20240427_120651_1756788379977.jpg": {
    "defaultSrc": "/images/timeline/optimized/20240427_120651_1756788379977-w960.webp",
    "srcSet": "/images/timeline/optimized/20240427_120651_1756788379977-w480.webp 480w, /images/timeline/optimized/20240427_120651_1756788379977-w960.webp 960w, /images/timeline/optimized/20240427_120651_1756788379977-w1600.webp 1600w",
    "placeholder": "data:image/webp;base64,UklGRsQAAABXRUJQVlA4ILgAAABwBQCdASogABIAPu1irVAppSQisBgIATAdiWoAnTMw1F4JDjTR9T1ujYcmhVfteeklXjOAAP7ql3S332flVQ4LhPEVzrcmIVtJ+QJ45Kv1sCTuCN1x9wFdSud7f2CJuKDq//62DxbCIPyvHX1XbAbiDIMnkDx3GZrjKWEtx0InCnY5kbDCEBkQtT5hc5cOnky8TUQxm1pJxOQWic/DxjuEex8IGguCswme0Z+uxRDIFBeJPMINWAAA",
    "width": 960,
    "height": 540,
    "aspectRatio": 1.7761989342806395
  },
  "timeline/20240508_203952_1756776021190.jpg": {
    "defaultSrc": "/images/timeline/optimized/20240508_203952_1756776021190-w960.webp",
    "srcSet": "/images/timeline/optimized/20240508_203952_1756776021190-w480.webp 480w, /images/timeline/optimized/20240508_203952_1756776021190-w960.webp 960w, /images/timeline/optimized/20240508_203952_1756776021190-w1600.webp 1600w",
    "placeholder": "data:image/webp;base64,UklGRsAAAABXRUJQVlA4ILQAAADwBACdASogABIAPu1kqE2ppaOiMAgBMB2JZAC7MtpC6pLkRk8i7ecAcKrTtuKfrjQA4eVDXahz9iqwT3hsN54MuIkNOO5GL3Rwv70QnsVzuihyahiOs3I8e7NnKOy4OiMQnT3T8otMT/CjHzCxdjTf9Wsvq8sRbwPcllsx4xBOCyiYeTQOX2cP0ykY2HdF2eftqb3mRDUX4LiqZ9uJNvxGZ6wISqlZsi/T+AYFhAIQ1IYoAAA=",
    "width": 960,
    "height": 540,
    "aspectRatio": 1.7761989342806395
  },
  "timeline/20241023_132525_1756776021189.jpg": {
    "defaultSrc": "/images/timeline/optimized/20241023_132525_1756776021189-w960.webp",
    "srcSet": "/images/timeline/optimized/20241023_132525_1756776021189-w480.webp 480w, /images/timeline/optimized/20241023_132525_1756776021189-w960.webp 960w, /images/timeline/optimized/20241023_132525_1756776021189-w1600.webp 1600w",
    "placeholder": "data:image/webp;base64,UklGRt4AAABXRUJQVlA4INIAAAAwBQCdASogABIAPu1kqU2ppaQiMAgBMB2JYwCdM0xCqzrqJqEvgPh24KgePKaTiWG+SAD9Sqk4F+Lgi+auXOyo6mHN/TKxG5UoSYo+a2BeAjURuPOfPgU6OJhcS97l+2TWEjSA0QZzPy5EUooXuJEOxitycWT/PXYRvY00r/rwSPj7X/oP7o1+gYIJ26DqyeAMLRZG6boWJ5jemRbHM9XO6gDK7170KjP4IRGJ+r8d/A9+vJnHR+rxB9R45JWAf3eb8TDvp3r/EZ94pjn6L4QAAAA=",
    "width": 960,
    "height": 540,
    "aspectRatio": 1.7761989342806395
  },
  "timeline/20241025_152323_1756776021189.jpg": {
    "defaultSrc": "/images/timeline/optimized/20241025_152323_1756776021189-w960.webp",
    "srcSet": "/images/timeline/optimized/20241025_152323_1756776021189-w480.webp 480w, /images/timeline/optimized/20241025_152323_1756776021189-w960.webp 960w, /images/timeline/optimized/20241025_152323_1756776021189-w1600.webp 1600w",
    "placeholder": "data:image/webp;base64,UklGRv4AAABXRUJQVlA4IPIAAADwBQCdASogABIAPu1iqE2ppaOiMAgBMB2JagCdMoBOYDVtFq7G0YlxLW6UCnbG8V0rgNfWhUsMAAD+j683h/f3ShMmx3hE122KRSH7I3/D98T0tHDdckGPD4Lx4T4ABKmt4xUIbOmDzpssJH6Vt+E58Qqmd60mLT+kRiYOgMqkMK7xjArllx6B0NbdGxMhS5X0B/SzN0gmnyAdgAkbvNcxi/4b68G6hIWqFGVt+8kmCHbgoqMo1oZNJ1TRZswArZCaKE8ZXCE8xDm+GYVrC8CFDZ29fXqoiAncA3pcwO2DNRFPuiTPdbKsV7YpwJdXuNwAAA==",
    "width": 960,
    "height": 540,
    "aspectRatio": 1.7772511848341233
  },
  "timeline/20250515_110951(0) (1)_1756775594777.jpg": {
    "defaultSrc": "/images/timeline/optimized/20250515_110951(0) (1)_1756775594777-w960.webp",
    "srcSet": "/images/timeline/optimized/20250515_110951(0) (1)_1756775594777-w480.webp 480w, /images/timeline/optimized/20250515_110951(0) (1)_1756775594777-w960.webp 960w, /images/timeline/optimized/20250515_110951(0) (1)_1756775594777-w1600.webp 1600w",
    "placeholder": "data:image/webp;base64,UklGRnIBAABXRUJQVlA4IGYBAABQBwCdASogABsAPu1wsFIppiSiqAgBMB2JbAC7Muu6NcAd1iwGVOwL0xLNh+UR0xCOudXA+VtfivgpY6Yq4o9vTG3sAP7xHgyxDt+NPc5xfrxbB1M4LYijLvQc+beb/Ie2thccNTiRc+qLay7zy8OCbmkulRoRtGiQkvzq0PsYpUld5UhYu0cE7ItFAx6VxBa+5LQpKMkEkWzqi/SvMR7kp3CBfO8URg8ZI5JktspI2IISvlkbia4IVlKa5/V3bPE9YWrUDmZX+PtM6Nt0R9uABWN2eyozz2aayKRsP8Gnq3jlQ1rhOEZ66o9gw9z03rDnKPeT5oeZdqv34jXt0luLksTN0HYIVXRM68EN5tBBMPgpb+WbK8w6+SO7K4orHXsVEPCNkZcbWSNEorZY7M8U7m5GFLEs0vZJysL0PeN46r9OItgFSmwkSRbf85Ghw+nco/DzfmW1l5/Ngafko1DzXCHlgAAA",
    "width": 960,
    "height": 804,
    "aspectRatio": 1.1940497335701599
  },
  "timeline/Generated Image September 01, 2025 - 10_25PM (1)_1756780361828.jpeg": {
    "defaultSrc": "/images/timeline/optimized/Generated Image September 01, 2025 - 10_25PM (1)_1756780361828-w960.webp",
    "srcSet": "/images/timeline/optimized/Generated Image September 01, 2025 - 10_25PM (1)_1756780361828-w480.webp 480w, /images/timeline/optimized/Generated Image September 01, 2025 - 10_25PM (1)_1756780361828-w960.webp 960w",
    "placeholder": "data:image/webp;base64,UklGRkYBAABXRUJQVlA4IDoBAABwBwCdASogABcAPu1iqU2ppaOiMAgBMB2JZgCdM1ZiwTAVoMsDTHtCCSQwh+lRsQSaLiNiPBSCmnbtTjl23ZZD1sYfAAD+Su49+DQih42/GCSXkVkPn/lfY9aBbbvCBnGlxc8E2eFM3qtDhUIcS2KfwRNXYWnGQDzJzC3bn7Vjzzrw9kwJRxObBWFkzdx2mSEvRESzNShsylv/o4S/w/gGXoWdoizlkVphy3FTKhkkjqDes+l12pC1jgL2iRjUKIQt439UJnIx8yczfCXXXvPEiIoF4SEVesDYKqOTcubPVPvKJ0tdV7l+NXTBFvmPc+ytcvG17mU7zk7vB/AxD/IqeS8pX0hMrjJdiib2hIDbTuMqzabq/F7FvD/Ifuw88gVbmkcT86+sOlBXMjUOzicqgQQ2JAE14AAAAA==",
    "width": 960,
    "height": 693,
    "aspectRatio": 1.3854166666666667
  },
  "timeline/IMG-20170811-WA0004_1756789814799.jpg": {
    "defaultSrc": "/images/timeline/optimized/IMG-20170811-WA0004_1756789814799-w960.webp",
    "srcSet": "/images/timeline/optimized/IMG-20170811-WA0004_1756789814799-w480.webp 480w, /images/timeline/optimized/IMG-20170811-WA0004_1756789814799-w960.webp 960w",
    "placeholder": "data:image/webp;base64,UklGRjYBAABXRUJQVlA4ICoBAAAQBgCdASogABgAPu1gqE2ppaOiMAgBMB2JagCBxHAGt9YJ2/v5OgM0C8Cd/BWJKVYRL+dunreSsAAA/us2b6KoOroZSPahhGJUl7iPBnur5t39TSFy4xVEGQT1RpXWAsZkOniijtt+0QrDD5U2aACyAWwVZC/msoWB4zCkW1cgalzIOxZmLO1ScB8vIHGDenXkBMPV+6p8T99o1Vy6FgSYbdHqtLOsSZNp68riFWrC7SzbYWzTLIqEFoTruAAp+ShdrCwmFBEdorH3IFghndaM78r3WbWcW0c5dDPvVRc7C+XlMCg6wasZmlOTlSeOCHu3NXqr0u2OuRYtDCz25LVeaIjd24P6vF0o2bdLNdp9DpcTiUozV5aRW7BJSYJB97HxLHdQwvTW+BAA",
    "width": 960,
    "height": 719,
    "aspectRatio": 1.3347236704900938
  },
  "timeline/IMG-20170814-WA0013_1756780825082.jpg": {
    "defaultSrc": "/images/timeline/optimized/IMG-20170814-WA0013_1756780825082-w480.webp",
    "srcSet": "/images/timeline/optimized/IMG-20170814-WA0013_1756780825082-w480.webp 480w",
    "placeholder": "data:image/webp;base64,UklGRoIBAABXRUJQVlA4IHYBAAAwCACdASogACsAPu1oqk2ppiQiKrgN+TAdiWwAnTlBU1VXNUOezZp7fKQZBo1uz3CmxtPhzih5m7bxWx/b6pLEJtsXWxleR+dfAAD+6/26us599uWNkaTLJrVj4csooX4UFWNm9tB9RSbUCaIibT1Njv/9guvRp6EWUrT5xObXdzZ3b/VLh4zesZ5d6GpIckybRLwBdX0q5H+214x62If+SRmElCwg7upEieHzJqn2sJQElaLrSfJFutgHIWH7MCoH6vWZnWzaXeCmiNW2PeUqhgn9G3jbOh7tXE7nOmXKfFZWhx0infkoyDdkHmprUqfPj73GWleD4xu4Rbi1935kFixmc8NTwiZjvf3ntj7LfBmWt4Hg/WekEvYB/PYvYDcGrRz0EcPsZ89eVa9TDXkTaGZ41W5dYBfHpHYkaUnQc6HZpfjZ993shUPVhUs+HxsL2Ywi81VXvJ5eu6NMLiTERTvL6r2IlZK3m3tLMS+EXskvYAAAAA==",
    "width": 480,
    "height": 640,
    "aspectRatio": 0.75
  },
  "timeline/IMG-20170814-WA0017_1756780825082.jpg": {
    "defaultSrc": "/images/timeline/optimized/IMG-20170814-WA0017_1756780825082-w960.webp",
    "srcSet": "/images/timeline/optimized/IMG-20170814-WA0017_1756780825082-w480.webp 480w, /images/timeline/optimized/IMG-20170814-WA0017_1756780825082-w960.webp 960w",
    "placeholder": "data:image/webp;base64,UklGRmYBAABXRUJQVlA4IFoBAAAQBwCdASogABgAPu1gp02ppSMiMAgBMB2JbACsMvKGdmIZ8zuxPqkyQvT22Fk8PX9UxpYvp35xMCOHHKxjSaM5gAD+t2XYtEze/+CY6RAmmPwtpYHWxJzvaChXCCLNZO727GGoMsm/t3uicfk+qRTWm5HApi5gE6h3ptu/PPUVKiZLZpaJkqSJcvCUpYgDBMkZBfdDW2DtOxVTPcEYrxNCoYiRpazj3CEtLzQjmgIGPRpdMs1Z7MUPe/dyjFuqoV3paDCeS2cRIsp0qFBMldvYniycIy+oWjc1HzR+lw0qfnXTvIB0oCzOGFZwgi+iuFAD28+XiEVYQYGiqvHSJXHrqiiScz29hWQOdmwa33IUjw+ikCQw+VuyzJLfHbT22s0XTy4GlGOsV9765jSXYNq5GObVZt4kZpHjKt9YM23CoG/0IyDUtEImge++dto0yPZIk67XYY5YUAAA",
    "width": 960,
    "height": 719,
    "aspectRatio": 1.3347236704900938
  },
  "timeline/IMG-20181105-WA0008_1756780506780.jpg": {
    "defaultSrc": "/images/timeline/optimized/IMG-20181105-WA0008_1756780506780-w960.webp",
    "srcSet": "/images/timeline/optimized/IMG-20181105-WA0008_1756780506780-w480.webp 480w, /images/timeline/optimized/IMG-20181105-WA0008_1756780506780-w960.webp 960w, /images/timeline/optimized/IMG-20181105-WA0008_1756780506780-w1600.webp 1600w",
    "placeholder": "data:image/webp;base64,UklGRuoAAABXRUJQVlA4IN4AAABQBQCdASogABUAPu1iqE2ppaOiMAgBMB2JYwC2ygEYwQTXe+7ZX833QRc+VsVg/+YnNAAA/txM8/P7VznXTO2LPKp20jVU0g/nov5/lW1bHPUb3g6Dpg3Um6F3XVtpxLhqdSpb28/Zry/PRrZkPnHjQlH72dxsDj2pP2+sT0mS2pjVz/vwO6p02HNbwIUGZ4N+E++yoJ7V7rNe3Z0iCnL9Xvpwkq0kNH6oDvo3/duR4WncC05GYCMqp9C1uLHjGV3xTVhEr0oECcqA8MB9FglWr2zFnhhNWInKAE0XAAA=",
    "width": 960,
    "height": 640,
    "aspectRatio": 1.499531396438613
  },
  "timeline/IMG-20190908-WA0038_1756789644237.jpg": {
    "defaultSrc": "/images/timeline/optimized/IMG-20190908-WA0038_1756789644237-w960.webp",
    "srcSet": "/images/timeline/optimized/IMG-20190908-WA0038_1756789644237-w480.webp 480w, /images/timeline/optimized/IMG-20190908-WA0038_1756789644237-w960.webp 960w, /images/timeline/optimized/IMG-20190908-WA0038_1756789644237-w1600.webp 1600w",
    "placeholder": "data:image/webp;base64,UklGRvQAAABXRUJQVlA4IOgAAABwBgCdASogABIAPu1kqk+ppSOiMBgIATAdiWgAvQCK//xSAB8EqG9K9BUEnWa1XUblX70rOc5atEPYWwAA/uqWwLmXMyqMFIXz3SoteSHgZAVc3PfnX/PWeTZfoFMxIKAB3QjPg+rtbh21usdlAvDf8TDk/w5aCkPm1uFPxN2D0M2T/F/mJGIS2OpTGTooplfJ8F8u/WhNown92soIyePSbNXBTGiLXC348XTqS6dU2brmEN08VFPbk1YfT9q0fciM0YUMymp7AI3N+10eCvwPyUEHs3suYQVYONU3LbWSrefMLFPIy0AA",
    "width": 960,
    "height": 540,
    "aspectRatio": 1.7777777777777777
  },
  "timeline/IMG-20191110-WA0025_1756789697282.jpg": {
    "defaultSrc": "/images/timeline/optimized/IMG-20191110-WA0025_1756789697282-w960.webp",
    "srcSet": "/images/timeline/optimized/IMG-20191110-WA0025_1756789697282-w480.webp 480w, /images/timeline/optimized/IMG-20191110-WA0025_1756789697282-w960.webp 960w, /images/timeline/optimized/IMG-20191110-WA0025_1756789697282-w1600.webp 1600w",
    "placeholder": "data:image/webp;base64,UklGRsAAAABXRUJQVlA4ILQAAAAQBQCdASogABgAPu1srFEppaQiqAqpMB2JQBUk5ofqB2HGNreIw7IPdUG1/GCKs/gAAP6eh/q/MY1Q5DNzVEES7GahL8aN1tXSVpW5mgdBHN6gHoHK/9MSvYBegLXJLFrHEjCNVYrTxulhKC+HALeciQuKLSDSV7JglBGRz+FyzaVM4UqC5RqJMusul8NzXWzotEaF7mC7b1Cnih2AZB54L+y6h1j83zKaokYjUc5/8YuMAAA=",
    "width": 960,
    "height": 720,
    "aspectRatio": 1.3333333333333333
  },
  "timeline/IMG-20191122-WA0013_1756780506778.jpg": {
    "defaultSrc": "/images/timeline/optimized/IMG-20191122-WA0013_1756780506778-w960.webp",
    "srcSet": "/images/timeline/optimized/IMG-20191122-WA0013_1756780506778-w480.webp 480w, /images/timeline/optimized/IMG-20191122-WA0013_1756780506778-w960.webp 960w, /images/timeline/optimized/IMG-20191122-WA0013_1756780506778-w1600.webp 1600w",
    "placeholder": "data:image/webp;base64,UklGRjgBAABXRUJQVlA4ICwBAACwBgCdASogABgAPu1iqE2ppaOiMAgBMB2JYwC1G2Q6jdJ8zwLF/7FRl08YqK1Q3MXJllS7fRjV++vSkSwLhAD+jTeiXX7wv0vfeKBbc3sUhjqVjluQQDDSduuX3JsV3pjhugfYyuFrTHwXtRvUf8PNHPjolJ0yuBawG18ZW5+CIkXKTZblYxhOH1qfINNMqQOYEZUSN1GyZn/pC755S2PEhzZXQnuTnrYmlfQbZdoLtK8o+tjdpc1+cT2KMtIc84nUTyQhNzdq1AcOVxTdd4Kel41k1v5TPCiP5kuKoAz9buL7vInY6m/K0kL/ed1D+dunFbON3VjdZQyg1a+86jXfjzaBWIiBpwn8SZw1AcgWEbKHt/+Wj7An2+lfqRqB4lf+gFW23XK9V14AAAA=",
    "width": 960,
    "height": 720,
    "aspectRatio": 1.3333333333333333
  },
  "timeline/IMG-20200111-WA0007_1756780521102.jpg": {
    "defaultSrc": "/images/timeline/optimized/IMG-20200111-WA0007_1756780521102-w960.webp",
    "srcSet": "/images/timeline/optimized/IMG-20200111-WA0007_1756780521102-w480.webp 480w, /images/timeline/optimized/IMG-20200111-WA0007_1756780521102-w960.webp 960w, /images/timeline/optimized/IMG-20200111-WA0007_1756780521102-w1600.webp 1600w",
    "placeholder": "data:image/webp;base64,UklGRiABAABXRUJQVlA4IBQBAACQBgCdASogABIAPu1gqE2ppaOiMAgBMB2JQBWGZl4Dt/PDDuCyps8ifx2yw8lupSZUXjm7gqhiS3a84qAAAP6Y7SsAaz6z3z8o8x4OKK0tzTjxyifrbOQrnQD09POHxZ/23drb1fNv9NxKSp6jF712V1rPL5fKhEMDa1qpzhnq+rXx+6pVo5Vee8kLn+dlKqfwS7wBmRr4qziQCWmABS0DQ2jjFXNYx3M3KSuWxVXw9BvgFCYxK7hrOnvLQddmPAzp33WBg/omp2IQR4TLWXSdROaAQ4FWdgvM/6B6n56dT76LAjgEGXJnVrLR2SBLQHOKr/U7veBCFlpylI7AlF6tUMPMjriuTKrOvSLv9KNwVifbAAA=",
    "width": 960,
    "height": 540,
    "aspectRatio": 1.7777777777777777
  },
  "timeline/IMG-20220807-WA0018_1756776767995.jpg": {
    "defaultSrc": "/images/timeline/optimized/IMG-20220807-WA0018_1756776767995-w960.webp",
    "srcSet": "/images/timeline/optimized/IMG-20220807-WA0018_1756776767995-w480.webp 480w, /images/timeline/optimized/IMG-20220807-WA0018_1756776767995-w960.webp 960w, /images/timeline/optimized/IMG-20220807-WA0018_1756776767995-w1600.webp 1600w",
    "placeholder": "data:image/webp;base64,UklGRsYAAABXRUJQVlA4ILoAAACQBQCdASogABIAPu1gq1AppSOisBgIATAdiUAWI9vwwAazxtjPuq3C7RU0eRL0RLC8OPkjDADWmKs3blHyDVo75wbLZ9Yg52XWNJodqT/ac5n8S6H9yfYvUMEz2mZK+5nzu0DbEi75BP+2Oa6xjUPWljiNjIm2iAvOom8V4NASTnUgkqfAWg/1f+Xh5DKpj7SWEskqAGHp04wRLE+0xWPwJ60oluXXYSknYjaPVfQ22T/88HmVOdkQAAA=",
    "width": 960,
    "height": 540,
    "aspectRatio": 1.7761989342806395
  },
  "timeline/IMG_1219_1756777552748.jpg": {
    "defaultSrc": "/images/timeline/optimized/IMG_1219_1756777552748-w960.webp",
    "srcSet": "/images/timeline/optimized/IMG_1219_1756777552748-w480.webp 480w, /images/timeline/optimized/IMG_1219_1756777552748-w960.webp 960w, /images/timeline/optimized/IMG_1219_1756777552748-w1600.webp 1600w",
    "placeholder": "data:image/webp;base64,UklGRi4BAABXRUJQVlA4ICIBAABQBgCdASogABkAPu1mp02ppiOiMBgMATAdiWoAnTKDIQ7AMNe0AGIN+ct2/ZLo3YrSrmN4+H2ztrjgAAD+41jt1LljuQy/Ys7xhO5n58ZytSb/wRlSeaXgUxcZyn5ZBqvoKJKZ7naC8PWgtRxMgi+d4mvr+vJqGytgtAoXt1l/anh9v+1OgLwB+wKbUV+954iN+sgG+Xoa9SG5ln5Hkh/IesDXp+GrpO/VFzaC2mZ7/F6aOJhZr0+mmdhUS99Cr9Tk/FG8MMEGepkaHdWDpvyidkzpBnvXx9ExoQHrDg3yXalJeurpD6Xfimx45u776Fk3US+VIjecbG4s54RR/Q1OkOJFOsCuD+nIjIH4JGseJzlvSb7qx4Tqk7jnmiszoTYAAA==",
    "width": 960,
    "height": 756,
    "aspectRatio": 1.2692944683670089
  },
  "timeline/IMG_20160620_123802_1756789570118.jpg": {
    "defaultSrc": "/images/timeline/optimized/IMG_20160620_123802_1756789570118-w480.webp",
    "srcSet": "/images/timeline/optimized/IMG_20160620_123802_1756789570118-w480.webp 480w",
    "placeholder": "data:image/webp;base64,UklGRngBAABXRUJQVlA4IGwBAAAQBwCdASogACAAPu1epk2ppKMiMAgBMB2JZACsBvA1iPg3SfM4JR16In2bKF2h3Mxq1ayYCSpJMJh7jZFxYCp4gAD+8urq65ki6ih0QX9f6yg+eTOezykp48zO1/ci7GSANK8MX8OXyV/3+mfju80OXymHdHiH1dL10JuGmolXkxcQxUDywLg5ZP8vhENtl+cCuH9RxXb17LeA5Ux3vVBr2zSg129OZVbuynPr0IU+5FYd2XOePd5v7wIVP3uQewPvDu/nJDpuGboovbW0xi/wtZejHgfXmFFRTJTQzG9xOKiW0KYuofN1k+U6QWtb9KSAKXlZI8zdebXaI9/CfOdsNQiKWarrjWAKZKnIzQVcEtxTV+kpec7E4zRhPINF4Noc3qd6fXe8eTb4NXxs6XN8nLf+pLde42mWE2opvGPqXP165gXliNzTYbKFFuE/aoHplQLSzW+oiIk5PDJG2IIMlRS3/SKibLXzGAAA",
    "width": 480,
    "height": 480,
    "aspectRatio": 1
  },
  "timeline/IMG_20161030_232457_1756789364618.jpg": {
    "defaultSrc": "/images/timeline/optimized/IMG_20161030_232457_1756789364618-w960.webp",
    "srcSet": "/images/timeline/optimized/IMG_20161030_232457_1756789364618-w480.webp 480w, /images/timeline/optimized/IMG_20161030_232457_1756789364618-w960.webp 960w, /images/timeline/optimized/IMG_20161030_232457_1756789364618-w1600.webp 1600w",
    "placeholder": "data:image/webp;base64,UklGRigBAABXRUJQVlA4IBwBAADwBQCdASogABgAPu1mqU8ppaOiMBgIATAdiWYAsO2MlUUbW0tyZTSwYr8n8BY/r/Qwrle0xPDcYAD+55NOwc5+WFxFOfYy0sYzu4l5u+lhQ8vpWE0om4WpI4IBrJOejL90PHnTJsq2JGMdEzcbOaFEuuMF189xfrJMuP+6QoeS+ku+f+BXn5jyig8NgHYKOtJem+eTI05twEaSFyb+rXAILI7bAVav1FRJUd0Ihta624bD4fBk597Qf3I0NHoHeYge1RgGsrO9ChXPMpP7F1HiszH3/4RqZghARf4ardlvnd+iA/ZQGwusS3WY3LoB9FD/FZOfXw+z1O0RKNzv7sfwoQm0m7lWkeaG882Gml74O+1qBHxBPjAUdcAAAA==",
    "width": 960,
    "height": 720,
    "aspectRatio": 1.3333333333333333
  },
  "timeline/IMG_20161106_212705_1756789364617.jpg": {
    "defaultSrc": "/images/timeline/optimized/IMG_20161106_212705_1756789364617-w960.webp",
    "srcSet": "/images/timeline/optimized/IMG_20161106_212705_1756789364617-w480.webp 480w, /images/timeline/optimized/IMG_20161106_212705_1756789364617-w960.webp 960w, /images/timeline/optimized/IMG_20161106_212705_1756789364617-w1600.webp 1600w",
    "placeholder": "data:image/webp;base64,UklGRlYBAABXRUJQVlA4IEoBAACwBgCdASogABgAPu1gp02ppSMiMAgBMB2JZgDA3y6eAGmDZwFL72Xmfq/D5cQJ/4h2gW18q7WBqf1mwlAqAAD+qapgNT5qdG/Z53gTLYEGhqQeI+FWAwCpU7vA7n2/SlkzpvP2eT7dQZzZZ4xa671vEKlgpc3o6+1sMrjyvivnBq90XWqwKWsDH+NciPMfsIXUaPybNtdMYAO1H8JaNRDAuhXngi/YjKV2gHUynXRUJ1+DP5xNz/OPJBi0RDCBqTsftxJMAcCDve5WuOWVnnQvtbIOdDmyw6T37ifGVnAQ2mJWoa1LN+0hreqoeVPC2mzFjMT/s3CH6WHtrKjlz+1a/LTS3tiK+V6YasU+jst2G1WMYyGcz6AVShcnHxw/mA9ZxGPoHg89d2TEyp6G/MKgQX3epDfM+0J1phFNWDzZ5kKTNgH1+frn4AA=",
    "width": 960,
    "height": 720,
    "aspectRatio": 1.3333333333333333
  },
  "timeline/IMG_20170820_163622_1756780825081.jpg": {
    "defaultSrc": "/images/timeline/optimized/IMG_20170820_163622_1756780825081-w960.webp",
    "srcSet": "/images/timeline/optimized/IMG_20170820_163622_1756780825081-w480.webp 480w, /images/timeline/optimized/IMG_20170820_163622_1756780825081-w960.webp 960w, /images/timeline/optimized/IMG_20170820_163622_1756780825081-w1600.webp 1600w",
    "placeholder": "data:image/webp;base64,UklGRiYBAABXRUJQVlA4IBoBAAAwBgCdASogABgAPu1kqU2ppaQiMAgBMB2JYwALACwmd56C+JMog3YC75rNA9v95NLTarAeW6XPe4mQAP5mNAN7y87mad918cSPO8CXSdWrbU8l3xBFwGAlSo6b6I72kuMB+QBzbSzlXSSG9ESt6wqQalPYIEsMBxY39Q4D9+F1p4Cp/caWI6ohWDzkUVP56BVRhTRK+0XS5TYlMtChxyK+Z2AISLVO/UnihwpRFimTu4nvZVinvx/GXXsRLmL7/Q3x2Qhdj9q2XuOuyMeC62HX3Va/niwYQNdB6eKHtWwqGlYlueFcT2eBb/SSpVL8gg75zrNkZNJXzfwUGzKa0jykXQAo/snU57pqR4Td2Ly0VgACijjsyDSgAAA=",
    "width": 960,
    "height": 720,
    "aspectRatio": 1.3333333333333333
  },
  "timeline/IMG_20180811_194748_1756789697281.jpg": {
    "defaultSrc": "/images/timeline/optimized/IMG_20180811_194748_1756789697281-w960.webp",
    "srcSet": "/images/timeline/optimized/IMG_20180811_194748_1756789697281-w480.webp 480w, /images/timeline/optimized/IMG_20180811_194748_1756789697281-w960.webp 960w, /images/timeline/optimized/IMG_20180811_194748_1756789697281-w1600.webp 1600w",
    "placeholder": "data:image/webp;base64,UklGRtgAAABXRUJQVlA4IMwAAACQBQCdASogABgAPuVgpE2pJaOiMAwBIByJQBnHA9gjy2LE+fc7QZhbUb2qMIzZMRsu8B9gAAD3KuBNF273cCJiCrzfB3z4mMmEUQ0+iD0o+DEebb7tz4w6HUuTrcI2+53vZHkeYde/vsJQx+BN5a+iUFDWC49DnuwN/89LQNWO0Eo5jB4hH4l9LVx/Z/EoKo7YdNadassaOarSLvR9ACHuM5HEumfdKgAWjy7i5pCWW0oArIfOLw0BNK3HOQZ+q1gnbLQLyauU8xYAAAA=",
    "width": 960,
    "height": 720,
    "aspectRatio": 1.3333333333333333
  },
  "timeline/IMG_20190509_180536_1756789644236.jpg": {
    "defaultSrc": "/images/timeline/optimized/IMG_20190509_180536_1756789644236-w960.webp",
    "srcSet": "/images/timeline/optimized/IMG_20190509_180536_1756789644236-w480.webp 480w, /images/timeline/optimized/IMG_20190509_180536_1756789644236-w960.webp 960w, /images/timeline/optimized/IMG_20190509_180536_1756789644236-w1600.webp 1600w",
    "placeholder": "data:image/webp;base64,UklGRgIBAABXRUJQVlA4IPYAAACQBQCdASogABgAPu1mqk2ppaQiMAgBMB2JYwCuHdzS8NfygseLui0CTw0+/VaH2S5tJuafAAD+i9fmZSDEVgv3TCnqLF0yNlrmEOYpU7Qd619dEUc3M1hAjngEbA4eVPMWeO55yCMdFZI2+8wPKDCGLtKSOHnioMhRHpgKRYQHviIby5NWHntS8hJ0UdeKT/9VtQzUms0di+aCnUtth8jYGkDnrL1Dg/1aTQzNwbe9PmXN8g2vS5PS7DKBAVSaoZ+Q+IYGuHhMw7sfircy0gLlDHIT7SP72I0Qyuya3h+QYqZsVdXHX+gr+O5AAkjL1o/TJMoAAAA=",
    "width": 960,
    "height": 720,
    "aspectRatio": 1.3333333333333333
  },
  "timeline/IMG_2329-EDIT_1756777352943.jpg": {
    "defaultSrc": "/images/timeline/optimized/IMG_2329-EDIT_1756777352943-w960.webp",
    "srcSet": "/images/timeline/optimized/IMG_2329-EDIT_1756777352943-w480.webp 480w, /images/timeline/optimized/IMG_2329-EDIT_1756777352943-w960.webp 960w, /images/timeline/optimized/IMG_2329-EDIT_1756777352943-w1600.webp 1600w",
    "placeholder": "data:image/webp;base64,UklGRioBAABXRUJQVlA4IB4BAADwBQCdASogAB8APu1mrE+ppSQiMBgIATAdiWwAnTLhgAAe+JeHuSSm+fVNNFtXPZSWGbzO+PU+AAD57OCxk9Ider5vvoRASlIBO6gGP3+g99Ma5B2HRwYVz5m5pAGiu9Q0ZU/5Ixrc38wEiI6+iUzGS8Q7qgbkD7TyB/AV4fBjnWRQbwO7af0ANMoWg+a/iIWccD+NLdPU7ZNvRd5P3bQleFluLLstaPG26FjRFO8XawLvcL3lPqJe9L1Ax+AcPTA8eNXv0YrlFElNRNOVxgyVkYb/G4fYolKOToP/oid8gjuOe77wvhKD7oXF9H/hBn294VwDKS+SbJRxrZGNhm7Fzx57p7qyDdlZx8q2D/1lL+269HjWB3/i4zw3pAAA",
    "width": 960,
    "height": 931,
    "aspectRatio": 1.031084656084656
  },
  "timeline/IMG_2331_1756789866665.JPG": {
    "defaultSrc": "/images/timeline/optimized/IMG_2331_1756789866665-w960.webp",
    "srcSet": "/images/timeline/optimized/IMG_2331_1756789866665-w480.webp 480w, /images/timeline/optimized/IMG_2331_1756789866665-w960.webp 960w, /images/timeline/optimized/IMG_2331_1756789866665-w1600.webp 1600w",
    "placeholder": "data:image/webp;base64,UklGRgIBAABXRUJQVlA4IPYAAABQBgCdASogABwAPu1qsFAppiSisBgIATAdiWIAgr7R8VRSnPPJSDVMJwg9Tmhdg0r4k/Tvr/rNiSE44AD+7irUJXgqAJrhSApy4ABNNl8/jQeThtDUlQxmOvcgSbPiI2PhR0ntxHqKddax2GMZD/7ZY0JronIwgPTRkAcjg0vZcDFaie3SDp34RihSW85ObadM7VpRXByynaSWUNP70i4W58M4xuXfd4PN6B+S6GukYoWR56VDR0ASKcQOcMkQGEyxkyusSGehEcvl+JxJUAIZj5qjyWidutHP6lCIvG0tR8LlLpBljal1PvlFXMnIlxuotrXBAAA=",
    "width": 960,
    "height": 835,
    "aspectRatio": 1.1494708994708995
  },
  "timeline/Screenshot_20180831-101808__01_1756789720602.jpg": {
    "defaultSrc": "/images/timeline/optimized/Screenshot_20180831-101808__01_1756789720602-w960.webp",
    "srcSet": "/images/timeline/optimized/Screenshot_20180831-101808__01_1756789720602-w480.webp 480w, /images/timeline/optimized/Screenshot_20180831-101808__01_1756789720602-w960.webp 960w",
    "placeholder": "data:image/webp;base64,UklGRqoBAABXRUJQVlA4IJ4BAAAwBwCdASogAB8AA4BaJbACdMoMw2nVcYLtExBMgqkZyy4CVRTRPHY20UnBeAK3X0LY8XhKlGpRSiB04v0t0pNA/YAA/t8qxhJAXSOkOY4xFHT0Rn5JIVwrfDFk1H52LLnkw2MnPe/ORyex4AqQfjzer+0nfxuH90XhaUYafcU77zHQfEvohdIVJYskaK/8tqqiDJGA5MhdMnLw1NEUNgASL5884LX59vz3pCepPJV/R7iLyD3EEF7gxj/y7YCMzFYQUbJPKtl3OxtCJg3wC9g0FMRznUpukH1BTjwdd9aibQq8eNMZuDvIDdkhvddQ6nFEiui+Ncd8WQmNji6VulYLHwN+AlIw5ofG671t23jlqqWahbe/CHsJb14UFdy6HkPZpE33l4BCStGu760g5cr0nH5QnneW7xXqaZJAHSLALoXx6kBg+NyoVYsoKCfH6UbKy9j0rkGbxQVjGtATZljiixd9GyBGrxFyCD/zQ7XCdKjh48cHaOfd8MYcKboKCKRL8clrXHVaJf3qbIG649FVasdnbSfSkM1vfI0nAAA=",
    "width": 960,
    "height": 945,
    "aspectRatio": 1.0159924741298212
  },
  "timeline/Screenshot_20181124-163448__01_1756789364618.jpg": {
    "defaultSrc": "/images/timeline/optimized/Screenshot_20181124-163448__01_1756789364618-w960.webp",
    "srcSet": "/images/timeline/optimized/Screenshot_20181124-163448__01_1756789364618-w480.webp 480w, /images/timeline/optimized/Screenshot_20181124-163448__01_1756789364618-w960.webp 960w",
    "placeholder": "data:image/webp;base64,UklGRpIBAABXRUJQVlA4IIYBAABwBwCdASogACAAPu1kqk4ppaQiMAgBMB2JbACdMtrGTGAdkuZSrjbpc7fQ/GYAmLrq4azIelPBxER+0no5aU5/DBcEiAD+whg4bmr1HhW3nfRp7Etn93dvO/rqPziROZd/id01JEvAcPDjU1/ssTmCl6ZP2PTe6iaCYq1E142MsiJiEtdH20PZRN7o4zI7+1gylgUBae+/l6C0T3Xh6ABb8/ophNgMiYcVKjMJrzK3f4eZwRzi0AZu056I6yuze/+T+barnDYeXkOCTN9WbCROhU2pxaMICWxe8UquUeE9LYkrgSmuDRVpUtpH4FUvwjPOEzVOKoSKitv6C29ZTKNX4KGW30OvdA6rIuaM+u8IQfb3t9wH0cDLW1zKtfYJJj9bLGS8tA4NVWGOgVa5QMwNtcHTHxt82XE56ml20kD1/cJCV2lm8QXb2xoOGVdf18TUUhte3dTk+c3RUhhsY5JnzRennQZ+Lu3WSdjC6yksfVyiyxmNXjXnVC5mQhhUzHyISI0AAAA=",
    "width": 960,
    "height": 957,
    "aspectRatio": 1.0027855153203342
  },
  "timeline/Screenshot_20190129-080233_1756780061880.jpg": {
    "defaultSrc": "/images/timeline/optimized/Screenshot_20190129-080233_1756780061880-w960.webp",
    "srcSet": "/images/timeline/optimized/Screenshot_20190129-080233_1756780061880-w480.webp 480w, /images/timeline/optimized/Screenshot_20190129-080233_1756780061880-w960.webp 960w, /images/timeline/optimized/Screenshot_20190129-080233_1756780061880-w1600.webp 1600w",
    "placeholder": "data:image/webp;base64,UklGRuYAAABXRUJQVlA4INoAAADwBACdASogABIAPu1kqU2ppaOiMAgBMB2JQBYfv/1K4FFti8TUEkCMeL2Xn6A9fAAA/qjjqDW8asbw4JojGVM4jKsj5T4hQSSkSqUx6OJur4Cc8CWstZ2/AEWb7bXuYiHxfgE4GB60Bh/zPLZQUvzNrBfljQBbnEgvW+H1O5ct7KhKEHLs5WSMWHC4Q+NlfgifPd/D+P4CLSCMPiRbW1r0cTrj616aqLTir8Bo4TC9eoyEH0P6pdmBto+PLVs8se/LWx/loeQ6dj1UC3U0Mh8bXGDCFOZSGgAAAA==",
    "width": 960,
    "height": 530,
    "aspectRatio": 1.8098522167487685
  },
  "timeline/image_1756765291859.png": {
    "defaultSrc": "/images/timeline/optimized/image_1756765291859-w480.webp",
    "srcSet": "/images/timeline/optimized/image_1756765291859-w480.webp 480w",
    "placeholder": "data:image/webp;base64,UklGRiYBAABXRUJQVlA4IBoBAABQBgCdASogABUAPu1kqk+ppSOiMBgIATAdiWoAnTMRDwCbVSd4YHk6jQvXIuBvgn8+d54tI+TI7WwWAAD+5GDU/BISUYTMNxBap4xYr5xbUXKIFoxuZc+cAYEaorzmt5SpQ82fsjcP3rRW9GGSo1+UHorYWybtEiAoGPbjGBwZOTc+IQxIF0JTWFebAB3Dm/JvPsKhjFqFz/ijbkmQqSg565Kd6wts9vZ0b2WvEKSG6IEygMTrzZudEJDQYnPYxxfDKaVRU7kufw6fCJxO8od93pMbCxUXrox/RM3ma9ZBhN35N5OO4KTz3FBLYY7O4c8h3lNHecFz38pfbEMYZ4gm48NOHxeWhcYCSsROAy1rGNcfm9WZVZiAAAA=",
    "width": 480,
    "height": 313,
    "aspectRatio": 1.5355086372360844
  },
  "timeline/image_1756766255322.png": {
    "defaultSrc": "/images/timeline/optimized/image_1756766255322-w480.webp",
    "srcSet": "/images/timeline/optimized/image_1756766255322-w480.webp 480w",
    "placeholder": "data:image/webp;base64,UklGRq4BAABXRUJQVlA4IKIBAABwCQCdASogADkAPuVcp02pJSOiM/ZtUSAciWQAvnugQpBU/YcjmwP5DQo6yxLl1/H3JpGYtHlWDPExLSADB5vnxb8swz+h3nlSSZMojuqYb5BX9WAA/kWKKSVeNkNtAfcWULK4n2oTg+i0Uf8sZKT90NFBKyYj2tXU9e/7GsD1v0yec+JWf1YxvfZ2wpuHNBXAaO8xTWZe2fDpsEb+meXxCPFeyBshM36um5WUCXcSgv3oExy2xllOunxJUfdFFfjuwZoeBLUV1J6YfBXGynic00QCO+AyXSNi7qE2sizlK5pq7pxfIX+WSGk4uYaCKuGQHmSE5b0nzpO+/8FJ+LsMUin+/F55JPFFYqTOUaAslGSlJ06dRL+gwLGKoR3zKdFB5VCZHoC/rHACMYaEJ+YawpqUntqkfqDDTs2+qbxi4IZLf3tw7vCTbMr1/SGQFn7AJWSUS4EUNK5ERReb9ioH3P25qKXjQKNESois7I6iCag4xucQprBX5vJqajTKMWiACJC2VU0ZIVwCM5XYwe6k86JzvkWTwRUVknTh6QLBoAAA",
    "width": 480,
    "height": 852,
    "aspectRatio": 0.5630530973451328
  }
} as const;
